module.exports = {
  "extends": "tslint-ionic-rules",
  "rules": {
    // TODO: Move these into tslint-ionic-rules?
    "align": true,
    "await-promise": true,
    "ban-comma-operator": true,
    "encoding": true,
    "jsdoc-format": [true, "check-multiline-start"],
    "linebreak-style": [true, "LF"],
    "new-parens": true,
    "no-conditional-assignment": true,
    "no-debugger": true,
    "no-duplicate-super": true,
    "no-duplicate-switch-case": true,
    "no-empty": true,
    "no-extra-boolean-cast": true,
    "no-import-side-effect": true,
    "no-inferrable-types": true,
    "no-internal-module": true,
    "no-misused-new": true,
    "no-non-null-assertion": true,
    "no-sparse-arrays": true,
    "no-string-throw": true,
    "no-switch-case-fall-through": true,
    "no-unnecessary-type-assertion": true,
    "no-unsafe-finally": true,
    "no-var-keyword": true,
    "no-var-requires": true,
    "prefer-conditional-expression": true,
    "prefer-for-of": true,
    "use-isnan": true,

    // Not as important
    "adjacent-overload-signatures": true,
    "array-type": [true, "array"],
    "arrow-parens": [true, "ban-single-arg-parens"],
    "arrow-return-shorthand": true,
    "deprecation": { "options": true, "severity": "warning" },
    "import-spacing": true,
    "interface-over-type-literal": true,
    "member-access": [true, "no-public"],
    "no-consecutive-blank-lines": true,
    "no-console": true,
    "no-implicit-dependencies": [true, "optional"],
    "no-irregular-whitespace": true,
    "no-multi-spaces": true,
    "no-null-keyword": true,
    "no-redundant-jsdoc": true,
    "no-reference": true,
    "no-return-await": true,
    "no-this-assignment": [true, { "allowed-names": ["^self$"], "allow-destructuring": true }],
    "one-line": [true, "check-catch", "check-finally", "check-else"],
    "one-variable-per-declaration": true,
    "prefer-object-spread": true,
    "space-within-parens": 0,
    "trailing-comma": [true, { "multiline": { "objects": "always", "arrays": "always", "functions": "never", "typeLiterals": "always" }, "singleline": "never" }],

    // TODO: look at these later
    // "newline-before-return": true,
    // "no-unsafe-any": true,
    // "prefer-method-signature": true,
    // "restrict-plus-operands": true,
    // "strict-type-predicates": true,
  }
};
