/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  PlatformDropdown as IonlabPlatformDropdown
} from './components/ionlab-platform-dropdown/ionlab-platform-dropdown';

declare global {
  interface HTMLIonlabPlatformDropdownElement extends IonlabPlatformDropdown, HTMLElement {
  }
  var HTMLIonlabPlatformDropdownElement: {
    prototype: HTMLIonlabPlatformDropdownElement;
    new (): HTMLIonlabPlatformDropdownElement;
  };
  interface HTMLElementTagNameMap {
    "ionlab-platform-dropdown": HTMLIonlabPlatformDropdownElement;
  }
  interface ElementTagNameMap {
    "ionlab-platform-dropdown": HTMLIonlabPlatformDropdownElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "ionlab-platform-dropdown": JSXElements.IonlabPlatformDropdownAttributes;
    }
  }
  namespace JSXElements {
    export interface IonlabPlatformDropdownAttributes extends HTMLAttributes {
      androidActive?: boolean;
      iPhoneActive?: boolean;
      windowsActive?: boolean;
    }
  }
}

