name: CI

on:
  push:
    branches-ignore:
      - stable
  pull_request:
    branches-ignore:
      - stable

jobs:
  build-and-test:
    name: Build and Test (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node:
          - 18.x
          - 16.x
    steps:
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Restore Dependency Cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-dependency-cache-${{ hashFiles('**/package.json') }}
      - run: npm install
      - run: npm run bootstrap
      - run: npm run lint
      - run: npm test
